name: Publicar entradas de blog

on:
  push:
    branches:
      - main
    paths:
      - '_posts/*.md'  # Monitorea las entradas de blog en formato .md

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get install pandoc # Instalar Pandoc para convertir Markdown a HTML
    
    - name: Convert Markdown to HTML
      run: |
        for post in _posts/*.md; do
          # Convierte cada archivo Markdown a HTML
          pandoc $post -o blog/$(basename $post .md).html
        done
    
    - name: Commit and push HTML files
      run: |
        git config --global user.email mbsebastian23@gmail.com
        git config --global user.name splashdown561
        git add blog/*.html
        git commit -m "Nueva entrada de blog"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usamos el token proporcionado por GitHub Actions
